### ISSUE TITLE
Edge <= 17 401 unauthorized

### ISSUE THREAD

**Issue by jstrojil** [apokalipto/devise_saml_authenticatable#146]
Greetings,
we have managed to get the gem working and it is doing a great job on all browsers except Edge. 
Whenever the page loads on Edge 17.0 or lower, any AXAJ (GET) request will result in 401 Unauthorized - it must be something related to cookies/sessions.

I have tried it on local IDP SAML server the request will result in the following error:
```
Started GET "/saml/auth?SAMLRequest=hVJLT4NAEP4r3PaELH1AuykkhMakSTWmVQ9ezBSGlGTZxd1B6793wdZw0Hrd%2BV4z364sNLIVWUdHtcO3Di15mbVoqNYq18p2DZo9mve6wKfdNmFHolYEgdQFyKO2JKac86BzDBv0WgE4KeatnVCtoFf5hbPgEz5Gb9YJe4UwwmUYlX4cLWN%2FVh7AhylwHyGGRYwVzKuDg1rb4UZZAkUJm%2FBw6fOFz6PHcC5mM8HjF%2BY9uzCD8eSGM%2B%2FUSGVF75awziihwdZWKGjQCirEPrvbCgcUcFl7TGmvc1qjSRdasnTVo8WQzqT%2FHqlBghIIVsGYtvou497ZbNYPWtbFp5dJqT9yg0CYMDIdMu9WmwboerD%2BpS79aoAKMqBsjYpYcDE5l43lUL1rmvBEXq6bFkxt%2B%2BPhCQq6LDZG5dKdaodVek5%2FZfaHz890%2FO%2FSLw%3D%3D" for ::1 at 2019-08-06 17:44:19 +0200
Processing by SamlIdpController#new as */*
  Parameters: {"SAMLRequest"=>"hVJLT4NAEP4r3PaELH1AuykkhMakSTWmVQ9ezBSGlGTZxd1B6793wdZw0Hrd+V4z364sNLIVWUdHtcO3Di15mbVoqNYq18p2DZo9mve6wKfdNmFHolYEgdQFyKO2JKac86BzDBv0WgE4KeatnVCtoFf5hbPgEz5Gb9YJe4UwwmUYlX4cLWN/Vh7AhylwHyGGRYwVzKuDg1rb4UZZAkUJm/Bw6fOFz6PHcC5mM8HjF+Y9uzCD8eSGM+/USGVF75awziihwdZWKGjQCirEPrvbCgcUcFl7TGmvc1qjSRdasnTVo8WQzqT/HqlBghIIVsGYtvou497ZbNYPWtbFp5dJqT9yg0CYMDIdMu9WmwboerD+pS79aoAKMqBsjYpYcDE5l43lUL1rmvBEXq6bFkxt++PhCQq6LDZG5dKdaodVek5/ZfaHz890/O/SLw=="}
  Rendering /Users/george/.rvm/gems/ruby-2.6.3/bundler/gems/ruby-saml-idp-ec715b252e84/app/views/saml_idp/idp/new.html.erb
  Rendered /Users/george/.rvm/gems/ruby-2.6.3/bundler/gems/ruby-saml-idp-ec715b252e84/app/views/saml_idp/idp/new.html.erb (1.1ms)
Completed 200 OK in 9ms (Views: 8.6ms)

**AJAX request here**
Started GET "/saml/auth" for ::1 at 2019-08-06 17:44:25 +0200
Processing by SamlIdpController#new as */*
Completed 500 Internal Server Error in 4ms


  
NoMethodError (undefined method `unpack1' for nil:NilClass):
  
/Users/george/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/base64.rb:59:in `decode64'
/Users/george/.rvm/gems/ruby-2.6.3/bundler/gems/ruby-saml-idp-ec715b252e84/lib/saml_idp/controller.rb:54:in `decode_SAMLRequest'
/Users/george/.rvm/gems/ruby-2.6.3/bundler/gems/ruby-saml-idp-ec715b252e84/lib/saml_idp/controller.rb:49:in `validate_saml_request'
activesupport (5.2.3) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.3) lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
actionpack (5.2.3) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (5.2.3) lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
activesupport (5.2.3) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (5.2.3) lib/active_support/callbacks.rb:513:in `each'
activesupport (5.2.3) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (5.2.3) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.2.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.3) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.3) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.3) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
actionpack (5.2.3) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.3) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.3) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.3) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (5.2.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
railties (5.2.3) lib/rails/engine.rb:524:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started POST "/saml/auth" for ::1 at 2019-08-06 17:44:25 +0200
Processing by SamlIdpController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"k633Sn0xkXX8bavlruoYbEdRdWdbPMUimCJ4ISISrx8yDjRwOLk13BZ59lEqayvpludOE8GR3L8JWgSdTrMtFQ==", "SAMLRequest"=>"hVJLT4NAEP4r3PaELH1AuykkhMakSTWmVQ9ezBSGlGTZxd1B6793wdZw0Hrd+V4z364sNLIVWUdHtcO3Di15mbVoqNYq18p2DZo9mve6wKfdNmFHolYEgdQFyKO2JKac86BzDBv0WgE4KeatnVCtoFf5hbPgEz5Gb9YJe4UwwmUYlX4cLWN/Vh7AhylwHyGGRYwVzKuDg1rb4UZZAkUJm/Bw6fOFz6PHcC5mM8HjF+Y9uzCD8eSGM+/USGVF75awziihwdZWKGjQCirEPrvbCgcUcFl7TGmvc1qjSRdasnTVo8WQzqT/HqlBghIIVsGYtvou497ZbNYPWtbFp5dJqT9yg0CYMDIdMu9WmwboerD+pS79aoAKMqBsjYpYcDE5l43lUL1rmvBEXq6bFkxt++PhCQq6LDZG5dKdaodVek5/ZfaHz890/O/SLw==", "email"=>"asdad@asd.cz", "password"=>"[FILTERED]", "commit"=>"Sign in"}
  Rendering /Users/george/.rvm/gems/ruby-2.6.3/bundler/gems/ruby-saml-idp-ec715b252e84/app/views/saml_idp/idp/saml_post.html.erb
  Rendered /Users/george/.rvm/gems/ruby-2.6.3/bundler/gems/ruby-saml-idp-ec715b252e84/app/views/saml_idp/idp/saml_post.html.erb (0.7ms)
Completed 200 OK in 6ms (Views: 1.9ms)


Started GET "/saml/auth?SAMLRequest=hVJLT4NAEP4r3PaEbHk07QZICI1Jk2pMqx68mBGGlGTZxd1B6793QWs4aL3ufK%2BZb1MLnexFMdBR7fF1QEteYS0aarUqtbJDh%2BaA5q2t8GG%2Fy9iRqBdBIHUF8qgtiYhzHgyOYYNRKwAnxbyNE2oVjCq%2FcFY85HP0dpOxZ6xXPF5y9JM4qfwYeeivFzzxsYHmpYIogShyUGsH3CpLoChjIV%2Bsfb7y%2BfJ%2BkYg4FuHqiXmPLsxkHF5x5p06qawY3TI2GCU02NYKBR1aQZU4FDc74YACzmvPKf1lTm806UpLlqcjWkzpTP7vkTokqIEgDea09KuMW2ez3dxp2VYfXiGlfi8NAmHGyAzIvGttOqDLwcaXtvabCSrIgLItKmLB2eS7bKyn6l3ThCfySt31YFo7Hg9PUNF5sTmqlO5Ue2zy7%2FQXZn%2F4%2FEzn%2Fy7%2FBA%3D%3D" for ::1 at 2019-08-06 17:44:28 +0200
Processing by SamlIdpController#new as */*
  Parameters: {"SAMLRequest"=>"hVJLT4NAEP4r3PaEbHk07QZICI1Jk2pMqx68mBGGlGTZxd1B6793QWs4aL3ufK+Zb1MLnexFMdBR7fF1QEteYS0aarUqtbJDh+aA5q2t8GG/y9iRqBdBIHUF8qgtiYhzHgyOYYNRKwAnxbyNE2oVjCq/cFY85HP0dpOxZ6xXPF5y9JM4qfwYeeivFzzxsYHmpYIogShyUGsH3CpLoChjIV+sfb7y+fJ+kYg4FuHqiXmPLsxkHF5x5p06qawY3TI2GCU02NYKBR1aQZU4FDc74YACzmvPKf1lTm806UpLlqcjWkzpTP7vkTokqIEgDea09KuMW2ez3dxp2VYfXiGlfi8NAmHGyAzIvGttOqDLwcaXtvabCSrIgLItKmLB2eS7bKyn6l3ThCfySt31YFo7Hg9PUNF5sTmqlO5Ue2zy7/QXZn/4/Ezn/y7/BA=="}
  Rendering /Users/george/.rvm/gems/ruby-2.6.3/bundler/gems/ruby-saml-idp-ec715b252e84/app/views/saml_idp/idp/new.html.erb
  Rendered /Users/george/.rvm/gems/ruby-2.6.3/bundler/gems/ruby-saml-idp-ec715b252e84/app/views/saml_idp/idp/new.html.erb (1.0ms)
Completed 200 OK in 5ms (Views: 5.2ms)
```
Thanks a lot

**Comment by adamstegman** [comment]
I don't really understand how that could happen. Is Edge not including the cookies with the AJAX request? Can you inspect it in the browser?

The logs seem to be from the IdP, so they don't seem relevant here—am I missing anything there?

**Comment by jstrojil** [comment]
I think it is but it is sending out duplicate requests maybe?

Here are screenshots of what happens after logging in using Edge 17.

![Snímek obrazovky 2019-08-07 v 7 58 20](https://user-images.githubusercontent.com/14294916/62598386-82a12380-b8e9-11e9-9f5f-e3d3116c40c4.png)
![Snímek obrazovky 2019-08-07 v 7 58 37](https://user-images.githubusercontent.com/14294916/62598398-87fe6e00-b8e9-11e9-93a9-768350f2103f.png)
![Snímek obrazovky 2019-08-07 v 7 58 45](https://user-images.githubusercontent.com/14294916/62598403-8b91f500-b8e9-11e9-8d2a-ffd53d0205c1.png)
![Snímek obrazovky 2019-08-07 v 7 59 01](https://user-images.githubusercontent.com/14294916/62598410-8f257c00-b8e9-11e9-9a6f-6b3e4552d1ec.png)


The log is probably irrelevant but on keycloak, it doesn't work as well.

**Comment by adamstegman** [comment]
Is the request cross-origin? Or maybe Edge has more safeguards on localhost. That could explain the lack of cookies. I haven't had to solve that myself but some googling indicates that using `fetch` might include a parameter to fix it: https://github.com/github/fetch/issues/349#issuecomment-225699815.

I assume that before these AJAX calls, you authenticated with the SP normally via the browser.

**Comment by jstrojil** [comment]
Worked, thanks a lot.
