### ISSUE TITLE
Devise with :saml_authenticatable AND :database_authenticatable

### ISSUE THREAD

**Issue by marcelotto** [apokalipto/devise_saml_authenticatable#25]
I am working on an application, in which I want to use DeviseSamlAuthenticatable as the primary authentication strategy, but for users without an account at the Identity Provider, also use Devises database_authenticatable strategy to authenticate via application-specific accounts. But when both strategies activated with

```ruby
devise :saml_authenticatable, :database_authenticatable 
```

and a single

```ruby
devise_for :users
```

in the routes.rb, I get:

```
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:538:in `add_route': Invalid route name, already in use: 'new_user_session'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1561:in `add_route'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1536:in `decomposed_match'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1534:in `block in decomposed_match'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1419:in `block (2 levels) in member'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:816:in `scope'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1419:in `block in member'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1665:in `with_scope_level'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1415:in `member'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1534:in `decomposed_match'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1517:in `block in match'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1507:in `each'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1507:in `match'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:689:in `map_method'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:650:in `get'
    from vendor/bundle/ruby/2.2.0/gems/devise_saml_authenticatable-1.1/lib/devise_saml_authenticatable/routes.rb:5:in `block in devise_saml_authenticatable'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1198:in `block in resource'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1676:in `block (2 levels) in resource_scope'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:816:in `scope'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1676:in `block in resource_scope'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1665:in `with_scope_level'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1675:in `resource_scope'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1197:in `resource'
    from vendor/bundle/ruby/2.2.0/gems/devise_saml_authenticatable-1.1/lib/devise_saml_authenticatable/routes.rb:4:in `devise_saml_authenticatable'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:249:in `block (4 levels) in devise_for'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:249:in `each'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:249:in `block (3 levels) in devise_for'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:452:in `with_devise_exclusive_scope'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:248:in `block (2 levels) in devise_for'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:351:in `block in devise_scope'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:940:in `block in constraints'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:816:in `scope'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:940:in `constraints'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:350:in `devise_scope'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:247:in `block in devise_for'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `each'
    from vendor/bundle/ruby/2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `devise_for'
    from config/routes.rb:74:in `block in <top (required)>'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `instance_exec'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `eval_block'
    from vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:401:in `draw'
    from config/routes.rb:1:in `<top (required)>'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `each'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `call'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `execute'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:27:in `updater'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/marcel/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from /Users/marcel/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /Users/marcel/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from /Users/marcel/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /Users/marcel/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from /Users/marcel/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
    from /Users/marcel/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from /Users/marcel/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    from /Users/marcel/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
    from config/environment.rb:5:in `<top (required)>'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from config.ru:3:in `block in <main>'
    from vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
    from vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
    from config.ru:in `new'
    from config.ru:in `<main>'
    from vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
    from vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
    from vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
    from vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
    from vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/server.rb:61:in `app'
    from vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/server.rb:139:in `log_to_stdout'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/server.rb:78:in `start'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

Since I know it is possible to chain different strategies with Warden, I wonder if and how it is possible to implement this with DeviseSamlAuthenticatable. 

Any help appreciated,
Marcel

**Comment by adamstegman** [comment]
There might be a better way, but we're currently mapping routes manually when using multiple authentication strategies.

``` ruby
devise_for :users, skip: :all
# database_authenticatable users
get "login" => "auth#login", as: :new_user_session
post "auth" => "auth#index", as: :user_session
get "auth/logout" => "auth#logout", as: :destroy_user_session

# opt-in saml_authenticatable
devise_scope :user do
  scope "users", controller: 'saml_sessions' do
    get :new, path: "saml/sign_in", as: :new_user_sso_session
    post :create, path: "saml/auth", as: :user_sso_session
    get :destroy, path: "sign_out", as: :destroy_user_sso_session
    get :metadata, path: "saml/metadata", as: :metadata_user_sso_session
    match :idp_sign_out, path: "saml/idp_sign_out", via: [:get, :post]
  end
end
```

We have our own `SamlSessionsController` in this case, you should be able to substitute `devise/saml_sessions` in that block.

Make sure you're aware of #22 when using database authentication.

**Comment by adamstegman** [comment]
I'm going to close this issue, please let me know if there's more to discuss!

**Comment by marcelotto** [comment]
First, thanks for your help. I didn't have time to try your suggestion yet. I will report my findings here, when I'm done.

**Comment by netpenthe** [comment]
@adamstegman I am trying to do something similar (saml + database authetnication).

I was wondering how you handle the "destroy_user_session" and  "destroy_user_sso_session" - do you just do a test to see how the user logged in and then just use one or the other path?

**Comment by adamstegman** [comment]
> do you just do a test to see how the user logged in and then just use one or the other path?

Basically, yes. Great question, that is probably important.

Our custom `SamlSessionsController` inherits from this gem's `Devise::SamlSessionsController` and adds an `after_filter` to store the warden `winning_strategy` so we know SAML was used to log in for this user.

``` ruby
class SamlSessionsController < Devise::SamlSessionsController
  after_filter :store_winning_strategy, only: :create

  private

  def store_winning_strategy
    warden.session(:user)[:strategy] = warden.winning_strategies[:user].class.name.demodulize.underscore.to_sym
  end
end
```

Our logout button uses `destroy_user_session_path`, which is a custom action that uses the default `sign_out` to sign out regardless of scope; then redirects to `destroy_internal_user_sso_session_path` if the winning strategy was SAML so that the user is signed out of the IdP.

**Comment by netpenthe** [comment]
ok great. thought that was the case.

**Comment by rsl** [comment]
this is a big pain when you're not skipping everything. we use passwords, logins, registrations, etc. manually maintaining these routes constantly seems... scary. devise upgrade routing changes will not propagate up to the routing. also, this info could be useful in the/a wiki.

**Comment by rsl** [comment]
adding what i just did. instead of skipping all and rewriting all, i just skipped :saml_authenticatable and defined THOSE methods [which i used a custom controller for anyhow]. seems to be working good. i aliased the routing name by using as: 'saml_session' instead as well.

**Comment by sguha00** [comment]
@rsl Could you provide your `routes.rb` file? Thanks!

**Comment by rsl** [comment]
@sguha00 sure. here's the part that you prolly want to see: 

```
# Snip snip snip
devise_for :users, skip: [:registrations, :saml_authenticatable], controllers: {sessions: 'devise_sessions'}
# Manually add user editing but disallow registrations [above]
as :user do
  get 'users/edit' => 'devise_registrations#edit', as: 'edit_registration'
  patch 'users' => 'devise_registrations#update', as: 'registration'

  # To avoid conflict saml_authenticatable routes are manually defined here.
  # Also we override the controller.
  resource :session, as: 'saml_session', only: [], controller: 'devise_saml_sessions', path: '/companies/:id/saml' do
    get :new, path: 'sign_in', as: 'new'
    post :create, path: 'auth'
    match :destroy, path: 'sign_out', as: 'destroy', via: :get
    get :metadata, path: 'metadata'
    match :idp_sign_out, path: 'idp_sign_out', via: [:get, :post]
  end
end
```

**Comment by rsl** [comment]
note: there's problems with #update_with_password as well

**Comment by adamstegman** [comment]
I added a wiki page to discuss this in more detail: https://github.com/apokalipto/devise_saml_authenticatable/wiki/Supporting-multiple-authentication-strategies

**Comment by hammady** [comment]
> I added a wiki page to discuss this in more detail: https://github.com/apokalipto/devise_saml_authenticatable/wiki/Supporting-multiple-authentication-strategies

I think the wiki page needs to be modified after recent gem changes. It didn't work for me out of the box because the `sign_out` in the custom action causes the `SamlSessionsController` to halt early from the `verify_signed_out_user ` filter. Moving it in the non-SAML logout works because the `destroy_saml_session_path` redirection takes care of destroying the session.
For that guide to be complete, it should also contain the manual route that fixes the conflicting sign_out path with the `database_authenticatable`. Please see below (note that I added support for multiple idps as well).

```ruby
# app/controllers/universal_logout_controller.rb
# Support SSO and non-SSO logout
class UniversalLogoutController < ApplicationController
    def logout
        saml_sign_out = authenticated_with_saml?
        Rails.logger.debug("Logging out with SAML: #{saml_sign_out}")
        if saml_sign_out
            idp_entity_id = warden_session["idp_entity_id"]
            redirect_to destroy_saml_session_path({ idp_entity_id: idp_entity_id })
        else
            sign_out
            redirect_to after_sign_out_path_for(:user), notice: "You have been successfully logged out."
        end
    end
    
    private

    def authenticated_with_saml?
        Rails.logger.debug("Reading warden session: #{warden_session}")
        warden_session["strategy"] == "saml_authenticatable"
    rescue Warden::NotAuthenticated
        false
    end

    def warden_session
        @warden_session ||= warden.session(:user)
    end
end
```

```ruby
# config/routes.rb
Rails.application.routes.draw do
  ...
  devise_scope :user do
    get 'users/saml/sign_out', to: 'devise/saml_sessions#destroy', as: "destroy_saml_session"
  end
  delete 'logout', to: 'universal_logout#logout', as: 'logout'
  ...
end
```

```ruby
# config/initializers/devise.rb (or a new initializer)
# Remember the winning authentication strategy to use during logout
# Also remember the idp_entity_id of the winning saml strategy to use during logout
Devise::SamlSessionsController.class_eval do
  after_action :store_winning_strategy, only: [:create]
  private
  def store_winning_strategy
    warden.session(:user)["strategy"] = warden.winning_strategies[:user].class.name.demodulize.underscore
    warden.session(:user)["idp_entity_id"] = get_idp_entity_id(params) rescue nil
    Rails.logger.debug("Storing warden session: #{warden.session(:user)}")
  end
end
```

Here is my custom entity reader that expects `idp_entity_id` in both sign in and sign out requests:
```ruby
class SAMLIdpEntityIdReader < DeviseSamlAuthenticatable::DefaultIdpEntityIdReader
    # delegate to super if either params contain SAMLRequest or SAMLResponse
    def self.entity_id(params)
        if params[:SAMLRequest] || params[:SAMLResponse]
            super(params)
        elsif params[:idp_entity_id]
            params[:idp_entity_id]
        else
            raise 'No Idp Entity Id found'
        end
    end
end
```
SSO sign in links are generated like this (`SAML_IDPS_CONFIG` is a global variable holding all Idp info):
```ruby
<% unless SAML_IDPS_CONFIG.empty? %>
<p>
Looking for SSO? Click on one of the below configured Idps:
<ul>
<% SAML_IDPS_CONFIG.each do |issuer, config| %>
  <li>
    <%= link_to config['name'], new_saml_user_session_path({ idp_entity_id: issuer }) %>
  </li>
<% end %>
</ul>
</p>
<% end %>
```
